"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

# ----------------------
# BASE DIRECTORY
# ----------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------
# SECRET KEY & DEBUG
# ----------------------
SECRET_KEY = 'django-insecure-cw-93=2-!5raobze$m3$sd8w8bhxxlz08jq&%w+8e+er2h-4c^'

# DEBUG should be False in production
DEBUG = False

# Hosts allowed to access the site
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]  # Add production host here

# ----------------------
# APPLICATION DEFINITION
# ----------------------
INSTALLED_APPS = [
    "bookshelf",
    "relationship_app",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "csp",  # django-csp for Content Security Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # CSP Middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF Protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking Protection
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add template directories if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'

# ----------------------
# DATABASE
# ----------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ----------------------
# PASSWORD VALIDATION
# ----------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------
# INTERNATIONALIZATION
# ----------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------
# STATIC & MEDIA FILES
# ----------------------
STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ----------------------
# CUSTOM USER MODEL
# ----------------------
AUTH_USER_MODEL = "bookshelf.CustomUser"

# ----------------------
# SECURITY SETTINGS
# ----------------------
# Force all requests to HTTPS
SECURE_SSL_REDIRECT = True  # Redirect HTTP requests to HTTPS

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000  # One year in seconds
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Include all subdomains
SECURE_HSTS_PRELOAD = True  # Preload in browsers

# Cookies sent only over HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Browser XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Prevent content-type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# ----------------------
# CONTENT SECURITY POLICY (CSP)
# ----------------------
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")

# ----------------------
# COMMENTS & DOCUMENTATION
# ----------------------
# DEBUG=False prevents detailed error messages from leaking sensitive info
# SECURE_SSL_REDIRECT ensures all requests use HTTPS
# HSTS settings force browsers to only use HTTPS
# SESSION_COOKIE_SECURE & CSRF_COOKIE_SECURE protect cookies over HTTPS
# SECURE_BROWSER_XSS_FILTER enables XSS filtering in browsers
# SECURE_CONTENT_TYPE_NOSNIFF prevents MIME sniffing
# X_FRAME_OPTIONS prevents clickjacking
# CSP directives restrict allowed sources for scripts, styles, images, and fonts
